Insert into JETSPEED2.PAGE_SECURITY (PAGE_SECURITY_ID,PARENT_ID,PATH,NAME,VERSION,SUBSITE,USER_PRINCIPAL,ROLE_PRINCIPAL,GROUP_PRINCIPAL,MEDIATYPE,LOCALE,EXT_ATTR_NAME,EXT_ATTR_VALUE) values (1,1,'/page.security','page.security',null,null,null,null,null,null,null,null,null);

update PORTLET_APPLICATION set SECURITY_REF = NULL WHERE APP_NAME = 'pms-portlet'