package com.pms.dao.daoSql;

public class DocumentationSQLConstant
{

	public static final String INSERT_DOCUMENTATION_CONENT_SQL = "UPDATE PMS_DOCUMENTATIONS SET FILE_CONTENT = ? WHERE agency = ? AND FILE_KEY = ?";

	public static final String GET_DOCUMENTATION_CONTENT_SQL = "SELECT FILE_CONTENT FROM PMS_DOCUMENTATIONS WHERE agency = ? AND FILE_KEY = ?";

	public static final String GET_DOCUMENTATION_SQL = "SELECT ID,FILE_KEY,AGENCY,FILE_NAME,CREATE_TIME,FILE_TYPE,UPDATED_TIME, FILE_SIZE FROM PMS_DOCUMENTATIONS WHERE agency = ? AND FILE_KEY = ?";

	public static final String DELETE_DOCUMENTATION_SQL = "DELETE FROM PMS_DOCUMENTATIONS WHERE agency = ? AND FILE_KEY = ?";
}