package com.pms.dao.daoSql;

public class MaterialConsumeSQLConstant
{
	private static final String SEARCH_MATERIAL_HEADER = "m.ID AS M_ID,m.AGENCY AS M_AGENCY, m.MATERIAL_NAME AS M_MATERIAL_NAME, m.DISPLAY_NAME AS M_DISPLAY_NAME, m.MATERIAL_BRAND AS M_MATERIAL_BRAND, m.MATERIAL_TYPE AS M_MATERIAL_TYPE, m.MATERIAL_UNIT AS M_MATERIAL_UNIT, m.MATERIAL_ICON AS M_MATERIAL_ICON";

	private static final String SEARCH_REPOSITORY_HEADER = "mr.ID AS MR_ID, mr.SERIAL_NUMBER AS MR_SERIAL_NUMBER,mr.AGENCY AS MR_AGENCY, mr.MATERIAL_NAME AS MR_MATERIAL_NAME, mr.DISPLAY_NAME AS MR_DISPLAY_NAME, mr.MATERIAL_BRAND AS MR_MATERIAL_BRAND, mr.MATERIAL_TYPE AS MR_MATERIAL_TYPE, mr.MATERIAL_UNIT AS MR_MATERIAL_UNIT, mr.MATERIAL_ICON AS MR_MATERIAL_ICON, mr.PURCHASE_PRICE AS MR_PURCHASE_PRICE, mr.SALE_PRICE AS MR_SALE_PRICE, mr.PURCHASE_DATE AS MR_PURCHASE_DATE,mr.PURCHASE_AMOUNT AS MR_PURCHASE_AMOUNT, mr.SALED_AMOUNT AS MR_SALED_AMOUNT, mr.PRODUCTION_DATE AS MR_PRODUCTION_DATE,mr.EXPIRATION_DATE AS MR_EXPIRATION_DATE";

	public static final String INSERT_REPOSITORY_SQL = "INSERT INTO PMS_MATERIALS_CONSUME(WORK_ORDER_ID, SERVICE_DAILY_ID, MATERIAL_REPOSITORY_ID,CONSUMED_AMOUNT) VALUES(?,?,?,?)";

	public static final String INSERT_MATERIAL_SQL = "INSERT INTO PMS_MATERIALS_CONSUME(WORK_ORDER_ID, SERVICE_DAILY_ID, MATERIAL_ID,CONSUMED_AMOUNT) VALUES(?,?,?,?)";

	public static final String SEARCH_SQL_BY_WO_ID = "SELECT mc.CONSUMED_AMOUNT AS CONSUMED_AMOUNT, " + SEARCH_MATERIAL_HEADER + "," + SEARCH_REPOSITORY_HEADER
			+ "  FROM PMS_MATERIALS_CONSUME mc LEFT JOIN PMS_MATERIALS_REPOSITORY mr ON mc.MATERIAL_REPOSITORY_ID = mr.ID LEFT JOIN PMS_MATERIALS m ON mc.MATERIAL_ID = m.ID WHERE mc.WORK_ORDER_ID = ?";

	public static final String SEARCH_SQL_BY_WO_REPO_IDS = "SELECT mc.CONSUMED_AMOUNT AS CONSUMED_AMOUNT, " + SEARCH_REPOSITORY_HEADER + " FROM PMS_MATERIALS_CONSUME mc LEFT JOIN PMS_MATERIALS_REPOSITORY mr ON mc.MATERIAL_REPOSITORY_ID = mr.ID WHERE mc.WORK_ORDER_ID = ? AND mc.MATERIAL_REPOSITORY_ID =?";

	public static final String SEARCH_SQL_BY_WO_MATERIAL_IDS = "SELECT mc.CONSUMED_AMOUNT AS CONSUMED_AMOUNT, " + SEARCH_MATERIAL_HEADER + " FROM PMS_MATERIALS_CONSUME mc LEFT JOIN PMS_MATERIALS m ON mc.MATERIAL_ID = m.ID WHERE mc.WORK_ORDER_ID = ? AND mc.MATERIAL_ID =?";

	public static final String SEARCH_SQL_BY_WO_SERVICE_IDS = "SELECT mc.CONSUMED_AMOUNT AS CONSUMED_AMOUNT, "+ SEARCH_MATERIAL_HEADER + "," + SEARCH_REPOSITORY_HEADER + " FROM PMS_MATERIALS_CONSUME mc LEFT JOIN PMS_MATERIALS_REPOSITORY mr ON mc.MATERIAL_REPOSITORY_ID = mr.ID LEFT JOIN PMS_MATERIALS m ON mc.MATERIAL_ID = m.ID WHERE mc.WORK_ORDER_ID = ? AND mc.SERVICE_DAILY_ID = ?";
}