package com.pms.dao.daoSql;

public class SerialNumberSQLConstant
{
	public static final String SEARCH_SERIAL_NUM_LIST = "SELECT ID, AGENCY, CATEGORY, TYPE, LENGTH, SEQUENCE, VALUE, PARENT_ID FROM PMS_SERIAL_NUMBER WHERE AGENCY=? AND PARENT_ID IS NULL";

	public static final String DELETE_SERIAL_NUM_CONSTITUENTS = "DELETE FROM PMS_SERIAL_NUMBER WHERE PARENT_ID=?";
}