package com.pms.dao.daoSql;

public class ServiceMappingSQLConstant
{
	private static final String SEARCH_SERVICE_MAPPING_SQL_HEADER_4_DEFAULT = "SELECT DISTINCT sm.AGENCY AS SM_AGENCY, "
			+ " s.ID AS S_ID, s.AGENCY AS S_AGENCY, s.SERVICE_NAME AS S_SERVICE_NAME, s.DESCRIPTION AS S_DESCRIPTION, s.IS_ENABLE AS S_IS_ENABLE, s.SERVICE_PRICE AS S_SERVICE_PRICE"
			+ " FROM PMS_SERVICES_MAPPING sm INNER JOIN PMS_SERVICES s ON sm.AGENCY = s.AGENCY AND sm.SERVICE_ID = s.ID ";

	public static final String SEARCH_DEFAULT_SERVICE_MAPPINGS = SEARCH_SERVICE_MAPPING_SQL_HEADER_4_DEFAULT
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_BASIC_ID = 0 AND s.IS_ENABLE = 1";

	public static final String SEARCH_DEFAULT_SERVICE_MAPPING = SEARCH_SERVICE_MAPPING_SQL_HEADER_4_DEFAULT
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_BASIC_ID = 0 AND sm.SERVICE_ID = ? AND s.IS_ENABLE = 1";

	private static final String SEARCH_SERVICE_MAPPING_SQL_HEADER_WITH_BRAND_DETAIL = "SELECT DISTINCT sm.AGENCY AS SM_AGENCY, "
			+ " s.ID AS S_ID, s.AGENCY AS S_AGENCY, s.SERVICE_NAME AS S_SERVICE_NAME, s.DESCRIPTION AS S_DESCRIPTION, s.IS_ENABLE AS S_IS_ENABLE, s.SERVICE_PRICE AS S_SERVICE_PRICE,"
			+ " b.ID AS B_ID, b.AGENCY AS B_AGENCY, b.CATEGORY AS B_CATEGORY, b.BRAND AS B_BRAND, b.MODEL AS B_MODEL, b.PUBLISH AS B_PUBLISH, b.LEV AS B_LEV, b.LOGO AS B_LOGO ,"
			+ " d.ID AS D_ID, d.AGENCY AS D_AGENCY, d.NAME AS D_NAME, d.COLORS AS D_COLORS, d.OUTPUT_VOLUME AS D_OUTPUT_VOLUME, d.INLET_FORM AS D_INLET_FORM, d.GEARBOX AS D_GEARBOX, d.PICTURES AS D_PICTURES"
			+ " FROM (((PMS_SERVICES_MAPPING sm INNER JOIN PMS_SERVICES s ON sm.AGENCY = s.AGENCY AND sm.SERVICE_ID = s.ID) "
			+ " INNER JOIN PMS_BRAND_DETAIL d ON sm.AGENCY = d.AGENCY AND sm.BRAND_DETAIL_ID = d.ID) "
			+ " INNER JOIN PMS_BRAND_BASIC b ON d.AGENCY = b.AGENCY AND d.BRAND_BASIC_ID = b.ID)";

	private static final String SEARCH_SERVICE_MAPPING_SQL_HEADER_WITH_BRAND_BASIC = "SELECT DISTINCT sm.AGENCY AS SM_AGENCY, "
			+ " s.ID AS S_ID, s.AGENCY AS S_AGENCY, s.SERVICE_NAME AS S_SERVICE_NAME, s.DESCRIPTION AS S_DESCRIPTION, s.IS_ENABLE AS S_IS_ENABLE, s.SERVICE_PRICE AS S_SERVICE_PRICE,"
			+ " b.ID AS B_ID, b.AGENCY AS B_AGENCY, b.CATEGORY AS B_CATEGORY, b.BRAND AS B_BRAND, b.MODEL AS B_MODEL, b.PUBLISH AS B_PUBLISH, b.LEV AS B_LEV, b.LOGO AS B_LOGO"
			+ " FROM ((PMS_SERVICES_MAPPING sm INNER JOIN PMS_SERVICES s ON sm.AGENCY = s.AGENCY AND sm.SERVICE_ID = s.ID) "
			+ " INNER JOIN PMS_BRAND_BASIC b ON sm.AGENCY = b.AGENCY AND sm.BRAND_BASIC_ID = b.ID) ";

	public static final String SEARCH_BRAND_SERVICE_MAPPING_SQL_4_BASIC = SEARCH_SERVICE_MAPPING_SQL_HEADER_WITH_BRAND_BASIC
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_BASIC_ID = ? AND sm.SERVICE_ID = ? AND s.IS_ENABLE = 1";

	public static final String SEARCH_BRAND_SERVICE_MAPPINGS_SQL_4_BASIC = SEARCH_SERVICE_MAPPING_SQL_HEADER_WITH_BRAND_BASIC
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_BASIC_ID = ? AND s.IS_ENABLE = 1";

	public static final String SEARCH_BRAND_SERVICE_MAPPINGS_SQL_4_DETAIL = SEARCH_SERVICE_MAPPING_SQL_HEADER_WITH_BRAND_DETAIL
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_DETAIL_ID = ? AND s.IS_ENABLE = 1";

	public static final String SEARCH_BRAND_SERVICE_MAPPING_SQL_4_DETAIL = SEARCH_SERVICE_MAPPING_SQL_HEADER_WITH_BRAND_DETAIL
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_DETAIL_ID = ? AND sm.SERVICE_ID = ? AND s.IS_ENABLE = 1";

	public static final String SEARCH_MATERIAL_SERVICE_MAPPINGS_SQL_4_DEFAULT = "SELECT sm.MATERIAL_AMOUNT AS SM_MATERIAL_AMOUNT, m.ID AS M_ID, m.AGENCY AS M_AGENCY, m.MATERIAL_NAME AS M_MATERIAL_NAME, m.DISPLAY_NAME AS M_DISPLAY_NAME, m.MATERIAL_BRAND AS M_MATERIAL_BRAND, m.MATERIAL_TYPE AS M_MATERIAL_TYPE, m.MATERIAL_UNIT AS M_MATERIAL_UNIT, m.MATERIAL_ICON AS M_MATERIAL_ICON "
			+ "FROM ((PMS_SERVICES_MAPPING sm INNER JOIN PMS_SERVICES s ON sm.AGENCY = s.AGENCY AND sm.SERVICE_ID = s.ID)"
			+ "INNER JOIN PMS_MATERIALS m ON sm.AGENCY = m.AGENCY AND sm.MATERIAL_ID = m.ID)"
			+ "WHERE sm.AGENCY = ? AND sm.BRAND_BASIC_ID = 0 AND sm.SERVICE_ID = ? AND s.IS_ENABLE = 1";

	public static final String SEARCH_MATERIAL_SERVICE_MAPPINGS_SQL_4_BASIC = "SELECT sm.MATERIAL_AMOUNT AS SM_MATERIAL_AMOUNT, m.ID AS M_ID, m.AGENCY AS M_AGENCY, m.MATERIAL_NAME AS M_MATERIAL_NAME, m.DISPLAY_NAME AS M_DISPLAY_NAME, m.MATERIAL_BRAND AS M_MATERIAL_BRAND, m.MATERIAL_TYPE AS M_MATERIAL_TYPE, m.MATERIAL_UNIT AS M_MATERIAL_UNIT, m.MATERIAL_ICON AS M_MATERIAL_ICON"
			+ " FROM (((PMS_SERVICES_MAPPING sm INNER JOIN PMS_SERVICES s ON sm.AGENCY = s.AGENCY AND sm.SERVICE_ID = s.ID) "
			+ " INNER JOIN PMS_MATERIALS m ON sm.AGENCY = m.AGENCY AND sm.MATERIAL_ID = m.ID) "
			+ " INNER JOIN PMS_BRAND_BASIC b ON sm.AGENCY = b.AGENCY AND sm.BRAND_BASIC_ID = b.ID) "
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_BASIC_ID = ? AND sm.SERVICE_ID = ? AND s.IS_ENABLE = 1";

	public static final String SEARCH_MATERIAL_SERVICE_MAPPINGS_SQL_4_DETAIL = "SELECT sm.MATERIAL_AMOUNT AS SM_MATERIAL_AMOUNT, m.ID AS M_ID, m.AGENCY AS M_AGENCY, m.MATERIAL_NAME AS M_MATERIAL_NAME, m.DISPLAY_NAME AS M_DISPLAY_NAME, m.MATERIAL_BRAND AS M_MATERIAL_BRAND, m.MATERIAL_TYPE AS M_MATERIAL_TYPE, m.MATERIAL_UNIT AS M_MATERIAL_UNIT, m.MATERIAL_ICON AS M_MATERIAL_ICON"
			+ " FROM (((PMS_SERVICES_MAPPING sm INNER JOIN PMS_SERVICES s ON sm.AGENCY = s.AGENCY AND sm.SERVICE_ID = s.ID) "
			+ " INNER JOIN PMS_MATERIALS m ON sm.AGENCY = m.AGENCY AND sm.MATERIAL_ID = m.ID) "
			+ " INNER JOIN PMS_BRAND_DETAIL d ON sm.AGENCY = d.AGENCY AND sm.BRAND_DETAIL_ID = d.ID) "
			+ " WHERE sm.AGENCY = ? AND sm.BRAND_DETAIL_ID = ? AND sm.SERVICE_ID = ? AND s.IS_ENABLE = 1";

	public static final String CREATE_SERVICE_MAPPING_SQL = "INSERT INTO PMS_SERVICES_MAPPING(AGENCY, BRAND_BASIC_ID, BRAND_DETAIL_ID, SERVICE_ID, MATERIAL_ID, MATERIAL_AMOUNT) VALUES(?,?,?,?,?,?)";

	public static final String DELETE_SERVICE_MAPPING_SQL_4_BASIC = "DELETE FROM PMS_SERVICES_MAPPING WHERE AGENCY = ? AND BRAND_BASIC_ID = ? AND SERVICE_ID = ?";

	public static final String DELETE_SERVICE_MAPPING_SQL_4_DETAIL = "DELETE FROM PMS_SERVICES_MAPPING WHERE AGENCY = ? AND BRAND_DETAIL_ID = ? AND SERVICE_ID = ?";

	public static final String DELETE_SERVICE_MAPPING_SQL_4_BASIC_REF = "DELETE FROM PMS_SERVICES_MAPPING WHERE AGENCY = ? AND BRAND_BASIC_ID = ?";

	public static final String DELETE_SERVICE_MAPPING_SQL_4_DETAIL_REF = "DELETE FROM PMS_SERVICES_MAPPING WHERE AGENCY = ? AND BRAND_DETAIL_ID = ?";

	public static final String DELETE_SERVICE_MAPPING_SQL_4_SERVICE_REF = "DELETE FROM PMS_SERVICES_MAPPING WHERE AGENCY = ? AND SERVICE_ID = ?";

	public static final String DELETE_SERVICE_MAPPING_SQL_4_MATERIAL_REF = "DELETE FROM PMS_SERVICES_MAPPING WHERE AGENCY = ? AND MATERIAL_ID = ?";
}