package com.pms.dao.daoSql;

public class SystemAccountSQLConstant
{
	public static final String CREATE_PRINCIPAL = "INSERT INTO PMS_PRINCIPAL(AGENCY,LOGIN_NAME,DISPLAY_NAME,ICON,IS_ADMIN,IS_ENABLE) VALUES(?,?,?,?,?,?)";

	public static final String CREATE_CREDENTIAL = "INSERT INTO PMS_CREDENTIAL(AGENCY,LOGIN_NAME,PASSWORD,CHANGE_NEXT_LOGIN,UPDATE_DATE,EXPIRE_DATE) VALUES(?,?,?,?,?,?)";

	public static final String DELETE_PRINCIPAL = "DELETE FROM PMS_PRINCIPAL WHERE AGENCY = ? AND LOGIN_NAME = ?";

	public static final String DELETE_CREDENTIAL = "DELETE FROM PMS_CREDENTIAL WHERE AGENCY = ? AND LOGIN_NAME = ?";

	public static final String UPDATE_CREDENTIAL = "UPDATE PMS_CREDENTIAL SET PASSWORD = ? , UPDATE_DATE = ? , EXPIRE_DATE = ? , CHANGE_NEXT_LOGIN = ? WHERE AGENCY = ? AND LOGIN_NAME = ?";

	public static final String UPDATE_PRINCIPAL = "UPDATE PMS_PRINCIPAL SET DISPLAY_NAME = ?, ICON = ? , IS_ADMIN = ?, IS_ENABLE = ? WHERE AGENCY = ? AND LOGIN_NAME = ?";

	public static final String SELECT_PRINCIPAL = "SELECT * FROM  PMS_PRINCIPAL WHERE AGENCY = ? AND LOGIN_NAME = ?";

	public static final String SELECT_ALL_PRINCIPALS = "SELECT * FROM  PMS_PRINCIPAL WHERE AGENCY = ?";

	public static final String SELECT_ALL_ACTIVE_PRINCIPALS = "SELECT * FROM  PMS_PRINCIPAL WHERE AGENCY = ? AND IS_ENABLE = 1";

	public static final String SELECT_CREDENTIAL = "SELECT * FROM PMS_CREDENTIAL WHERE AGENCY = ? AND LOGIN_NAME = ?";

	public static final String CREATE_RELATIONSHIP_WITH_GROUP = "INSERT INTO PMS_PRINCIPAL_GROUP(AGENCY, PRINCIPAL,GROUP_ID) VALUES(?,?,?)";

	public static final String GET_RELATIONSHIP_WITH_GROUP = "SELECT GROUP_ID FROM PMS_PRINCIPAL_GROUP WHERE AGENCY = ? AND PRINCIPAL = ?";

	public static final String DELETE_RELATIONSHIP_WITH_GROUP = "DELETE FROM PMS_PRINCIPAL_GROUP WHERE AGENCY = ? AND PRINCIPAL = ?";
}