package com.pms.dao.daoSql;

public class WorkOrderStatusSQLConstant
{
	public final static String GET_WORK_ORDER_STATUS_BY_AGENCY = "SELECT * FROM PMS_WO_STATUS WHERE AGENCY=?";
	
	public final static String GET_ENABLE_WORK_ORDER_STATUS_BY_AGENCY = "SELECT * FROM PMS_WO_STATUS WHERE AGENCY=? AND IS_ENABLE=1";
	
	public final static String GET_WORK_ORDER_STATUS_BY_AGENCY_STATUS_NAME = "SELECT * FROM PMS_WO_STATUS WHERE AGENCY=? AND STATUS_NAME=?";

	public final static String CREATE_WORK_ORDER_STATUS = "INSERT INTO PMS_WO_STATUS (AGENCY, STATUS_NAME, IS_ENABLE) VALUES(?,?,?)";

	public final static String DELETE_WORK_ORDER_STATUS = "DELETE FROM PMS_WO_STATUS WHERE AGENCY = ? AND STATUS_NAME = ?";

	public final static String UPDATE_WORK_ORDER_STATUS = "UPDATE PMS_WO_STATUS SET IS_ENABLE = ? WHERE AGENCY = ? AND STATUS_NAME = ?";

	public final static String GET_WORK_ORDER_STATUS_VALUES_BY_AGENCY_STATUS_NAME = "SELECT * FROM PMS_WO_STATUS_VALUE WHERE AGENCY=? AND STATUS_NAME=?";

	public final static String CREATE_WORK_ORDER_STATUS_VALUE = "INSERT INTO PMS_WO_STATUS_VALUE (AGENCY, STATUS_NAME, VALUE_NAME, IS_ENABLE) VALUES(?,?,?,?)";

	public final static String DELETE_WORK_ORDER_STATUS_VALUE = "DELETE FROM PMS_WO_STATUS_VALUE WHERE AGENCY = ? AND STATUS_NAME = ?";
}